### ISSUE TITLE
Ripples is not defined in index.html

### ISSUE THREAD

**Issue by KartikKannapur** [donlion/Google-Ripples#1]
Nice project !!
When I open index.html I get a simple button. The data-ripple effect doesn't seem to be working.
If I'm doing something wrong here, we can update the documentation.

![screenshot from 2014-08-15 02 36 24](https://cloud.githubusercontent.com/assets/2961049/3927073/233d77d6-23f7-11e4-9874-0f29eee4ead0.png)

**Comment by donlion** [comment]
Actually, it should show you the ripple, but since it's a very small button, it might be impossible to see it.
Anyways, I've updated the index.html file, so it's a little easier :)
Thanks for your engagement!

**Comment by KartikKannapur** [comment]
Thanks for the quick update.
Glad to help out.
